### ISSUE TITLE
Unhandled IOError exceptions

### ISSUE THREAD

**Issue by lpinner** [caskater4/pyrocopy#9]
pyrocopy doesn't handle IOErrors when copying. For example:

```
pyrocopy %USERPROFILE% %TEMP%\test\pyro -q

Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Python\Scripts\pyrocopy.exe", line 9, in <module>
    sys.exit(main())
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python27\site-packages\pyrocopy\__init__.py", line 57, in main
    results = pyrocopy.copy(args.source, args.destination, includeFiles=args.includefiles, includeDirs=args.includedirs, excludeFiles=args.excludefiles, excludeDirs=args.excludedirs, level=args.level, followLinks=args.followlinks, forceOverwrite=args.force, preserveStats=(not args.nostat))
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python27\site-packages\pyrocopy\pyrocopy.py", line 263, in copy
    preserveStats=preserveStats)
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python27\site-packages\pyrocopy\pyrocopy.py", line 999, in _copyFile
    with open(src, 'rb') as fsrc:
IOError: [Errno 13] Permission denied: 'C:\\Users\\USERNAME\\NTUSER.DAT'
```

**Comment by caskater4** [comment]
PR is merged. Thanks!
